// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHkj57iaSEEVFJ-5DPzDNQcsVa20wvOlY',
    appId: '1:681813772960:web:177f93d022ef3456cc57c5',
    messagingSenderId: '681813772960',
    projectId: 'badmintonapp-5502a',
    authDomain: 'badmintonapp-5502a.firebaseapp.com',
    storageBucket: 'badmintonapp-5502a.firebasestorage.app',
    measurementId: 'G-15MDRQHT22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUNt5nECaIBoAvhhJkKSECybSEOgKo6_4',
    appId: '1:681813772960:android:57bfc0c2e491b5ddcc57c5',
    messagingSenderId: '681813772960',
    projectId: 'badmintonapp-5502a',
    storageBucket: 'badmintonapp-5502a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7KwmpU0Ef6Y16kI-K4PubWHaTB9X5Mh8',
    appId: '1:681813772960:ios:c7d55c20cea1ee26cc57c5',
    messagingSenderId: '681813772960',
    projectId: 'badmintonapp-5502a',
    storageBucket: 'badmintonapp-5502a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7KwmpU0Ef6Y16kI-K4PubWHaTB9X5Mh8',
    appId: '1:681813772960:ios:c7d55c20cea1ee26cc57c5',
    messagingSenderId: '681813772960',
    projectId: 'badmintonapp-5502a',
    storageBucket: 'badmintonapp-5502a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHkj57iaSEEVFJ-5DPzDNQcsVa20wvOlY',
    appId: '1:681813772960:web:33ea84e0813d0512cc57c5',
    messagingSenderId: '681813772960',
    projectId: 'badmintonapp-5502a',
    authDomain: 'badmintonapp-5502a.firebaseapp.com',
    storageBucket: 'badmintonapp-5502a.firebasestorage.app',
    measurementId: 'G-9M9845M2NW',
  );

}