// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz4i9nSZHRwgBBbuZTaP3U47UVXzeWJWI',
    appId: '1:806797846218:web:1fd03731d2cc77074f3633',
    messagingSenderId: '806797846218',
    projectId: 'badmintonapp-8de08',
    authDomain: 'badmintonapp-8de08.firebaseapp.com',
    storageBucket: 'badmintonapp-8de08.firebasestorage.app',
    measurementId: 'G-KQHCXP9LLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0WqZvlR88JHId7sisKQZiPCznJX4JrXc',
    appId: '1:806797846218:android:c7c2dcd926638aa94f3633',
    messagingSenderId: '806797846218',
    projectId: 'badmintonapp-8de08',
    storageBucket: 'badmintonapp-8de08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1n49NRDO9CCwITEOO45IOgAyiy00qOHE',
    appId: '1:806797846218:ios:6b4d3fcf668a9b0c4f3633',
    messagingSenderId: '806797846218',
    projectId: 'badmintonapp-8de08',
    storageBucket: 'badmintonapp-8de08.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1n49NRDO9CCwITEOO45IOgAyiy00qOHE',
    appId: '1:806797846218:ios:6b4d3fcf668a9b0c4f3633',
    messagingSenderId: '806797846218',
    projectId: 'badmintonapp-8de08',
    storageBucket: 'badmintonapp-8de08.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz4i9nSZHRwgBBbuZTaP3U47UVXzeWJWI',
    appId: '1:806797846218:web:fd6e272a32f458c84f3633',
    messagingSenderId: '806797846218',
    projectId: 'badmintonapp-8de08',
    authDomain: 'badmintonapp-8de08.firebaseapp.com',
    storageBucket: 'badmintonapp-8de08.firebasestorage.app',
    measurementId: 'G-SX6J38TC4K',
  );
}
